//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingChallenge.Data.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CodingChallenge.Data.Resx.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EmptyListOfShapes {
            get {
                return ResourceManager.GetString("EmptyListOfShapes", resourceCulture);
            }
        }
        
        internal static string ShapesReport {
            get {
                return ResourceManager.GetString("ShapesReport", resourceCulture);
            }
        }
        
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        internal static string Shapes {
            get {
                return ResourceManager.GetString("Shapes", resourceCulture);
            }
        }
        
        internal static string Perimeter {
            get {
                return ResourceManager.GetString("Perimeter", resourceCulture);
            }
        }
        
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        internal static string CUADRADO {
            get {
                return ResourceManager.GetString("CUADRADO", resourceCulture);
            }
        }
        
        internal static string CUADRADO_PLURAL {
            get {
                return ResourceManager.GetString("CUADRADO_PLURAL", resourceCulture);
            }
        }
        
        internal static string CIRCULO {
            get {
                return ResourceManager.GetString("CIRCULO", resourceCulture);
            }
        }
        
        internal static string CIRCULO_PLURAL {
            get {
                return ResourceManager.GetString("CIRCULO_PLURAL", resourceCulture);
            }
        }
        
        internal static string TRIANGULO_EQUILATERO {
            get {
                return ResourceManager.GetString("TRIANGULO_EQUILATERO", resourceCulture);
            }
        }
        
        internal static string TRIANGULO_EQUILATERO_PLURAL {
            get {
                return ResourceManager.GetString("TRIANGULO_EQUILATERO_PLURAL", resourceCulture);
            }
        }
        
        internal static string TRAPECIO {
            get {
                return ResourceManager.GetString("TRAPECIO", resourceCulture);
            }
        }
        
        internal static string TRAPECIO_PLURAL {
            get {
                return ResourceManager.GetString("TRAPECIO_PLURAL", resourceCulture);
            }
        }
    }
}
